name: Fetch Daily Stock Data

on:
  schedule:
    - cron: '0 1 * * *' # Runs daily at 1 AM UTC
  workflow_dispatch: # Allows for manual trigger

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas

    - name: List files for debugging
      run: ls -R

    - name: Run script to fetch data
      run: python fetch_daily_stock_data.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add bsestock.csv
        git commit -m "Automated daily stock data fetch" || echo "No changes to commit"
        git push
